---
name: "Speedtest"
description: "Speedtest-cli addon"
version: 1.6.2
slug: "speedtest_addon"
init: false
boot: manual
startup: once
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
homeassistant_api: true
options:
  accept_eula: false
  accept_rgpd: false
  debug: false
  print_closest_servers: false
schema:
  accept_eula: bool
  accept_rgpd: bool
  server_id: int?
  debug: bool?
  print_closest_servers: bool?
url: https://github.com/MrSuicideParrot/hassio-speedtest-addon
image: ghcr.io/mrsuicideparrot/hassio-speedtest-addon-{arch}
